"""Include column expire target roles

Revision ID: fcf7aff6a7f5
Revises: 4b8d450e8360
Create Date: 2024-10-15 10:57:17.655680

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fcf7aff6a7f5"
down_revision = "4b8d450e8360"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rstuf_target_roles",
        sa.Column("expires", sa.DateTime(), nullable=False),
    )
    op.drop_index(
        "ix_rstuf_target_roles_rolename", table_name="rstuf_target_roles"
    )
    op.create_unique_constraint(None, "rstuf_target_roles", ["rolename"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rstuf_target_roles", type_="unique")
    op.create_index(
        "ix_rstuf_target_roles_rolename",
        "rstuf_target_roles",
        ["rolename"],
        unique=True,
    )
    op.drop_column("rstuf_target_roles", "expires")
    # ### end Alembic commands ###
